# Generated by Django 3.2.7 on 2021-09-11 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 18, 52, 4, 258317, tzinfo=utc)),
        ),
    ]
