# Generated by Django 3.2.7 on 2022-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_portfolio_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='TechStack',
        ),
    ]
